broker.id=2
listeners=SASL_SSL://127.0.0.1:19093
advertised.listeners=SASL_SSL://127.0.0.1:19093
security.inter.broker.protocol=SASL_SSL
sasl.mechanism.inter.broker.protocol=PLAIN
sasl.enabled.mechanisms=PLAIN
listener.name.sasl_ssl.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="broker" password="broker-secret" user_broker="broker-secret" user_admin="admin-secret" user_producer="producer-secret" user_consumer="consumer-secret";
ssl.keystore.type=PKCS12
ssl.keystore.location=workshop10/security/generated/broker2.p12
ssl.keystore.password=changeit
ssl.key.password=changeit
ssl.truststore.type=PKCS12
ssl.truststore.location=workshop10/security/generated/truststore.p12
ssl.truststore.password=changeit
ssl.client.auth=none
authorizer.class.name=kafka.security.authorizer.AclAuthorizer
super.users=User:admin;User:broker
allow.everyone.if.no.acl.found=false
log.dirs=common/data/security-broker2
zookeeper.connect=127.0.0.1:12181,127.0.0.1:12182,127.0.0.1:12183
offsets.topic.replication.factor=3
transaction.state.log.replication.factor=3
transaction.state.log.min.isr=2
default.replication.factor=3
min.insync.replicas=2
controlled.shutdown.enable=true
auto.create.topics.enable=false
