clusters=source,target
source.bootstrap.servers=127.0.0.1:19092,127.0.0.1:19093,127.0.0.1:19094
target.bootstrap.servers=127.0.0.1:39092,127.0.0.1:39093,127.0.0.1:39094
source->target.enabled=true
target->source.enabled=false
source->target.topics=orders|payments|audit-events
source->target.groups=training-group
replication.policy.class=org.apache.kafka.connect.mirror.IdentityReplicationPolicy
replication.factor=3
refresh.topics.interval.seconds=5
refresh.groups.interval.seconds=5
sync.topic.configs.enabled=true
sync.topic.acls.enabled=false
emit.heartbeats.enabled=true
emit.heartbeats.interval.seconds=5
heartbeats.topic.replication.factor=3
emit.checkpoints.enabled=true
emit.checkpoints.interval.seconds=5
checkpoints.topic.replication.factor=3
emit.offset-syncs.enabled=true
offset-syncs.topic.replication.factor=3
sync.group.offsets.enabled=true
sync.group.offsets.interval.seconds=5
offset.storage.replication.factor=3
config.storage.replication.factor=3
status.storage.replication.factor=3
