process.roles=controller
node.id=102
controller.quorum.voters=101@127.0.0.1:29101,102@127.0.0.1:29102,103@127.0.0.1:29103
listeners=CONTROLLER://127.0.0.1:29102
controller.listener.names=CONTROLLER
listener.security.protocol.map=CONTROLLER:PLAINTEXT
log.dirs=common/data/kraft-controller2
